---
name: "TestSuite"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: TestSuite
    runs-on: ubuntu-latest
    env:
        CC: clang
        CXX: clang++

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2
          submodules: 'recursive'

      - name: Build picotls and picoquic.
        run: |
          sudo apt-get install -y libssl-dev
          ./ci/build_picotls.sh
          ./ci/build_picoquic.sh
     
      - name: Build quicrq
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
          make

      - name: Perform Unit tests
        run: |
          ulimit -c unlimited -S
          pwd
          ./quicrq_t -S .. -P ../../picoquic && QRQRESULT=$? 
          if [ ${QRQRESULT} == 0 ]; then exit 0; fi;
          exit 1

