---
name: "TestSuiteClang"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: TestSuiteClang
    runs-on: ubuntu-latest
    env:
        CC: clang
        CXX: clang++

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2

      - name: Build quicrq
        run: |
          brew reinstall openssl
          export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
          cmake -S . -B build
          cmake --build build

      - name: Perform Unit tests
        run: |
          ulimit -c unlimited -S
          cd build
          make test && QRQRESULT=$?
          tail /home/runner/work/quicrq/quicrq/build/Testing/Temporary/LastTest.log
          if [ ${QRQRESULT} == 0 ]; then exit 0; fi;
          exit 1

