---
name: "TestMacOs"

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: TestMacOs
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2

      - name: Build quicrq
        run: |
          # brew reinstall openssl
          # export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
          cmake -S . -B build
          cmake --build build

      # Build quicrq and run tests
      - name: Perform Unit tests
        run: |
          ulimit -c unlimited -S
          cd build
          make test && QRQRESULT=$?
          if [ ${QRQRESULT} == 0 ]; then exit 0; fi;
          exit 1

